# Generated by Django 4.2.7 on 2023-12-02 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Please provide a brief description of skill required')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.charity')),
            ],
        ),
    ]
