# Generated by Django 4.2.7 on 2023-12-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charities', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestinskilldonated',
            name='skill_donated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_donated', to='volunteers.skilldonated'),
        ),
    ]
