# Generated by Django 4.2.7 on 2023-12-06 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charities', '0001_initial'),
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDonated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Please provide a brief description of skill you want to offer to donate')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_donator', to='app_auth.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='InterestInSkillRequired',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_required', to='charities.skillrequired')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='app_auth.volunteer')),
            ],
        ),
    ]
